use_frameworks!

platform :ios, '13.0'

target 'MarkdownViewKit_Example' do
  pod 'MarkdownViewKit', :path => '../'
  pod 'ZLFlexKit'
  target 'MarkdownViewKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
