use_frameworks!

platform :ios, '10.0'

target 'MarkdownViewKit_Example' do
  pod 'MarkdownViewKit', :path => '../'

  target 'MarkdownViewKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
